FROM node:18-alpine

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm install --production

COPY server.js .
COPY routes/ ./routes/
COPY controllers/ ./controllers/
COPY services/ ./services/

EXPOSE 5000

CMD ["node", "server.js"]
